# Generated by Django 4.1.9 on 2023-05-25 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusBill', models.CharField(max_length=225)),
                ('DeliveryTime', models.DateTimeField(blank=True, null=True)),
                ('DeliveryDestination', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=255)),
                ('Releasedate', models.DateField()),
                ('ContentBook', models.TextField()),
                ('PageNumber', models.IntegerField()),
                ('Price', models.FloatField()),
                ('BookImage', models.CharField(max_length=225)),
                ('Author', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=225)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('FullName', models.CharField(max_length=225, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleuser', to='Entity.role')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrole', to='Entity.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookuser', to='Entity.book')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbook', to='Entity.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=225)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookcomment', to='Entity.book')),
                ('CommentParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Entity.comment')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomment', to='Entity.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('StatusBuy', models.CharField(max_length=225)),
                ('PurchasedPrice', models.FloatField()),
                ('Bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billbought', to='Entity.bill')),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookbought', to='Entity.book')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbought', to='Entity.user')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.category'),
        ),
    ]
